server:
  port: 8080

spring:
  application:
    name: spring-rest-security
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/cybertek
    username: postgres
    password: 5432
